version: '3.8'

services:
  bookly:
    build: .
#    depends_on:
#      - db
    ports:
      - "8080:8080"
    environment:
#      DB_DSN: postgres://user:password@db:5432/course?sslmode=disable
      DB_DSN: postgres://ru:2595@host.docker.internal:5432/ru_DB?sslmode=disable
    command: ["./main"]

#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: course
#    ports:
#      - "5432:5432"